### ISSUE TITLE
Add yes | no handling for additional parameters in redis.conf

### ISSUE THREAD

**Issue by enbrnz** [owncloud-ansible/redis#7]
`redis_rdbcompression: "yes"`
https://github.com/owncloud-ansible/redis/blob/bdf60299e989cfcda3f03d2ff0299e388be2cfb4/defaults/main.yml#L37

`redis_appendonly: "no"`
https://github.com/owncloud-ansible/redis/blob/bdf60299e989cfcda3f03d2ff0299e388be2cfb4/defaults/main.yml#L45

**Comment by xoxys** [comment]
@enbrnz That should be fixed by the `ternay` filter. Or do you miss something?

**Comment by enbrnz** [comment]
LGTM!
